version: '2'
services:
  php:
    build:
      context: ./
      dockerfile: Dockerfile
    tty: true
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ./:/var/www/html
  mysql:
    image: mysql:5.7
    ports: 
      - 3306:3306
    tty: true 
    restart: unless-stopped 
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_USER=usuario
      - MYSQL_PASSWORD=1234
      - MYSQL_DATABASE=blog 
    volumes:
      - ./mysql:/var/lib/mysql
